User.create!([
  {email: "zcheins@gmail.com", encrypted_password: "$2a$10$xM0JAAuVO4SMbp1dIqE8oe7vuga2fotHRMEvOcsjq2Ixri7ToWey2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 38, current_sign_in_at: "2016-03-20 21:57:14", last_sign_in_at: "2016-03-20 07:48:57", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Zoe", last_name: "Heins", company_id: nil, admin: false, state: "AL"},
  {email: "dustin@gmail.com", encrypted_password: "$2a$10$obcL9ZTW2J7r/2PLXdM0M.W6.ChkaeauxiNABUn5b8O8ridpkB6li", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-02-21 20:10:07", last_sign_in_at: "2016-02-17 19:13:46", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Dustin", last_name: "Kubas", company_id: nil, admin: false, state: "IL"},
  {email: "john@gmail.com", encrypted_password: "$2a$10$JeAOQJxqlqcebxP8bx3pCeZNeeiBOASGNFrMDrT2pnDFUV5j4Jppe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-02-18 03:06:51", last_sign_in_at: "2016-02-18 02:36:55", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "John", last_name: "Doe", company_id: nil, admin: false, state: "VI"},
  {email: "meow@gmail.com", encrypted_password: "$2a$10$b286rdNiXuiSdh6xi7ImTOpW2Wx93koLBM3l8CrWob0zzi1OGemle", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2016-03-10 00:14:05", last_sign_in_at: "2016-03-10 00:00:01", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Katie", last_name: "Smith", company_id: nil, admin: false, state: "UL"},
  {email: "bark@gmail.com", encrypted_password: "$2a$10$tQIbA09m1O1PgZyb5iUbP..pva.L6vMGwaXmmp9NKY/BxBDAsRjBe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2016-03-14 16:50:39", last_sign_in_at: "2016-03-08 18:06:41", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Jim", last_name: "Halpert", company_id: nil, admin: false, state: "MN"},
  {email: "meep@gmail.com", encrypted_password: "$2a$10$0.bNbAFqIfwZvCiQfq461OHQIX29C2FBDvG30AaFK1NLGxt2LFatK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-08 18:46:13", last_sign_in_at: "2016-03-08 18:46:13", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Alex", last_name: "Daniels", company_id: nil, admin: false, state: "ID"},
  {email: "george@gmail.com", encrypted_password: "$2a$10$cvcWoDmZiCHiaZRWJBDJROkGzg4I/ca.1JPGbS9J8O8H41wP1sxRK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-11 03:02:23", last_sign_in_at: "2016-03-11 03:02:23", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "George", last_name: "Costanza", company_id: nil, admin: false, state: "NY"},
  {email: "derek@gmail.com", encrypted_password: "$2a$10$CgVFgL4tjnUewxGZkwgbjewJtClFAfYp3rsfIFJq5EXtkHdGkdr22", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-11 15:33:34", last_sign_in_at: "2016-03-11 15:33:34", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Sandy", last_name: "White", company_id: nil, admin: false, state: "TX"},
  {email: "lsdkjf@gmail.com", encrypted_password: "$2a$10$H0LNeAeFsOhGpheRxdEHcOP1tb2iUlyFiPf1aNojdwaLHEL4lXsYe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-12 22:42:14", last_sign_in_at: "2016-03-12 22:42:14", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Zoe", last_name: "Heins", company_id: nil, admin: false, state: "WA"},
  {email: "ed@gmail.com", encrypted_password: "$2a$10$0y/fxE4X03FZvA30FQl0s.iHz/T1HgEi3v2qGhddc02cSclVQdvKe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-14 17:05:13", last_sign_in_at: "2016-03-14 17:05:13", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Ed", last_name: "Stark", company_id: nil, admin: false, state: "UT"},
  {email: "zoe@gmail.com", encrypted_password: "$2a$10$cAS1L7GTjWYGHc03TJLepeSJzwKUcZT1vODd0mzbp8AepfNKY.mMa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-14 19:00:10", last_sign_in_at: "2016-03-14 19:00:10", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Ned", last_name: "White", company_id: nil, admin: false, state: "SC"},
  {email: "jenny@gmail.com", encrypted_password: "$2a$10$oWsUG2m28nOQzb3Kt7GhzO3J5ZrmIVLc9dt1oE4RPgkCWYovwTeNq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-15 19:50:34", last_sign_in_at: "2016-03-15 19:50:34", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Elijah", last_name: "Wood", company_id: nil, admin: false, state: "WY"},
  {email: "jack@gmail.com", encrypted_password: "$2a$10$brIyq93z516gaiz9OEOVReJVs7XZBNAIeckqv9tHuAJa4mL6Rv3La", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2016-03-16 17:45:04", last_sign_in_at: "2016-03-16 16:23:52", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Jack", last_name: "Daniels", company_id: nil, admin: false, state: "VT"},
  {email: "arya@yahoo.com", encrypted_password: "$2a$10$80FMD6ubPT2Z7a9Er5kN/OCOVZfM1XyQ.Nav1fTfkgXkf3q/Yum7e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-16 17:47:03", last_sign_in_at: "2016-03-16 17:47:03", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Arya", last_name: "Stark", company_id: nil, admin: false, state: "GA"},
  {email: "marie@yahoo.com", encrypted_password: "$2a$10$Risn9gny/SG/lmkmNuWWtu8kUfWvNLcvaL154WvGx.lvW6/0IOqhm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-16 17:48:58", last_sign_in_at: "2016-03-16 17:48:58", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Marie", last_name: "Jones", company_id: nil, admin: false, state: "MN"},
  {email: "selena@gmail.com", encrypted_password: "$2a$10$DX5m/AJV8N/5jqIuNHjp0eSI5XQegfHO/Z3o3GG3S54s5wDK/6EzS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-17 01:59:09", last_sign_in_at: "2016-03-17 01:59:09", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Selena", last_name: "Meyer", company_id: nil, admin: false, state: "MO"},
  {email: "jerry@gmail.com", encrypted_password: "$2a$10$rs75UzvPgWVP3FZHU2ZU5euRPr349SVEEjoi4VjeUAFoVEZcR5LXa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-17 16:32:28", last_sign_in_at: "2016-03-17 16:32:28", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Jerry", last_name: "S", company_id: nil, admin: false, state: "NC"},
  {email: "cris@gmail.com", encrypted_password: "$2a$10$lFHZ9/0jOtCWFh3h7xvON.f3kXeIa7/x4vevGX5pMQl.aQ9Yx2Qia", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-18 02:07:25", last_sign_in_at: "2016-03-18 02:07:25", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Zoe", last_name: "Heins", company_id: nil, admin: false, state: "IL"},
  {email: "olivia@gmail.com", encrypted_password: "$2a$10$NN8Yk7Xxb/bzgx81VLTLmuQHh0z2dutzMHh7cFOfLGITDB.Mrwg6q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-18 22:59:23", last_sign_in_at: "2016-03-18 22:59:23", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Olivia", last_name: "Johnson", company_id: nil, admin: false, state: "TX"},
  {email: "kat@gmail.com", encrypted_password: "$2a$10$oRkxTrkuHGXay2UiPu3pXO9dyD5dCwGwRqE4NGNbIrLv4QCHMQ7Ou", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2016-03-20 02:16:26", last_sign_in_at: "2016-03-20 02:16:26", current_sign_in_ip: "::1", last_sign_in_ip: "::1", first_name: "Kat", last_name: "Shepherd", company_id: nil, admin: false, state: "AL"}
])
Habit.create!([
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.89", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: nil, input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: nil, input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "2.79", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "1.48", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.21", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.21", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.21", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "3.33", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.13", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "0.13", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "public_transportation", value: "0.27", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "public_transportation", value: "0.27", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "air_travel", value: "0.08", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "0.0", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "2.07", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "1.38", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "1.38", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "1.38", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "1.38", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "12.78", input1: nil, input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "vehicle", value: "5.05", input1: "12500.0", input2: "22.0", input3: "8.89"},
  {user_id: 1, profile_id: 1, footprint_type: "public_transportation", value: "0.05", input1: "165.0", input2: "300.0", input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "air_travel", value: "0.74", input1: "3700.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "electricity", value: "8.43", input1: "1020.0", input2: "0.08", input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "heating", value: "0.42", input1: "200.0", input2: "4.02", input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "propane", value: "0.86", input1: "464.0", input2: "3.12", input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "home", value: "2.16", input1: "2323.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "meat", value: "0.86", input1: "1.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "dairy", value: "0.49", input1: "1.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "grains", value: "0.36", input1: "1.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "fruit", value: "0.3", input1: "1.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "other", value: "1.0", input1: "1.0", input2: nil, input3: nil},
  {user_id: 1, profile_id: 1, footprint_type: "natural_gas", value: "2.47", input1: "550.0", input2: "1.18", input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "natural_gas", value: "16.17", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "other", value: "0.36", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "fruit", value: "0.18", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "home", value: "0.0", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "meat", value: "0.43", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "dairy", value: "0.24", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "meat", value: "0.86", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "fruit", value: "0.18", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: nil, value: nil, input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "dairy", value: "0.24", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "vehicle", value: "2.28", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "public_transportation", value: "2.88", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "air_travel", value: "0.4", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "electricity", value: "20.38", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "natural_gas", value: "0.6", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "heating", value: "10.16", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "propane", value: "5.76", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "home", value: "1.86", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "meat", value: "0.43", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "dairy", value: "0.24", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "grains", value: "0.18", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "fruit", value: "0.15", input1: nil, input2: nil, input3: nil},
  {user_id: nil, profile_id: nil, footprint_type: "other", value: "0.5", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "vehicle", value: "2.69", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "public_transportation", value: "0.15", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "air_travel", value: "0.6", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "electricity", value: "6.79", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "natural_gas", value: "0.6", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "heating", value: "10.16", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "propane", value: "5.76", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "home", value: "1.86", input1: "2000.0", input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "meat", value: "0.86", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "dairy", value: "0.49", input1: nil, input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "grains", value: "0.18", input1: "0.5", input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "fruit", value: "0.15", input1: "0.5", input2: nil, input3: nil},
  {user_id: 2, profile_id: nil, footprint_type: "other", value: "1.0", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "dairy", value: "0.24", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "grains", value: "0.18", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "meat", value: "0.43", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "home", value: "1.86", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "natural_gas", value: "10.6", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "propane", value: "4.05", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "vehicle", value: "2.61", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "public_transportation", value: "1.2", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "air_travel", value: "0.4", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "electricity", value: "1.38", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "heating", value: "20.32", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "fruit", value: "0.15", input1: nil, input2: nil, input3: nil},
  {user_id: 3, profile_id: nil, footprint_type: "other", value: "0.5", input1: nil, input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "vehicle", value: "2.96", input1: "10000.0", input2: "30.0", input3: "8.89"},
  {user_id: 7, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "air_travel", value: "0.4", input1: "2000.0", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "electricity", value: "5.43", input1: "800.0", input2: "0.1", input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "natural_gas", value: "11.16", input1: "200.0", input2: "0.1", input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "heating", value: "2.03", input1: "200.0", input2: "1.0", input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "propane", value: "1.15", input1: "200.0", input2: "1.0", input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "home", value: "0.09", input1: "100.0", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "meat", value: "1.9", input1: "2.2", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "dairy", value: "0.29", input1: "0.6", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "grains", value: "0.36", input1: "1.0", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "fruit", value: "0.66", input1: "2.2", input2: nil, input3: nil},
  {user_id: 7, profile_id: nil, footprint_type: "other", value: "2.2", input1: "2.2", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "vehicle", value: "5.92", input1: "20000.0", input2: "30.0", input3: "8.89"},
  {user_id: 8, profile_id: nil, footprint_type: "public_transportation", value: "0.09", input1: "300.0", input2: "300.0", input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "air_travel", value: "6.0", input1: "30000.0", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "electricity", value: "1.22", input1: "180.0", input2: "0.1", input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "natural_gas", value: "4.46", input1: "80.0", input2: "0.1", input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "heating", value: "0.68", input1: "80.0", input2: "1.0", input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "propane", value: "0.23", input1: "40.0", input2: "1.0", input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "meat", value: "1.9", input1: "2.2", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "dairy", value: "0.19", input1: "0.4", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "grains", value: "0.86", input1: "2.4", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "fruit", value: "0.42", input1: "1.4", input2: nil, input3: nil},
  {user_id: 8, profile_id: nil, footprint_type: "other", value: "0.2", input1: "0.2", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "vehicle", value: "5.92", input1: "20000.0", input2: "30.0", input3: "8.89"},
  {user_id: 9, profile_id: nil, footprint_type: "public_transportation", value: "0.08", input1: "500.0", input2: "165.0", input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "air_travel", value: "0.8", input1: "4000.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "electricity", value: "20.38", input1: "3000.0", input2: "0.1", input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "natural_gas", value: "5.3", input1: "1000.0", input2: "1.0", input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "heating", value: "1.26", input1: "500.0", input2: "4.02", input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "propane", value: "1.15", input1: "200.0", input2: "1.0", input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "home", value: "0.93", input1: "1000.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "meat", value: "1.73", input1: "2.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "dairy", value: "0.49", input1: "1.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "grains", value: "0.72", input1: "2.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "fruit", value: "0.6", input1: "2.0", input2: nil, input3: nil},
  {user_id: 9, profile_id: nil, footprint_type: "other", value: "2.2", input1: "2.2", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "public_transportation", value: "6.0", input1: "20000.0", input2: "300.0", input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "air_travel", value: "4.0", input1: "20000.0", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "electricity", value: "5.43", input1: "800.0", input2: "0.1", input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "natural_gas", value: "5.58", input1: "100.0", input2: "0.1", input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "heating", value: "0.51", input1: "50.0", input2: "1.0", input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "propane", value: "0.29", input1: "50.0", input2: "1.0", input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "meat", value: "1.55", input1: "1.8", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "dairy", value: "0.88", input1: "1.8", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "grains", value: "0.43", input1: "1.2", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "fruit", value: "0.6", input1: "2.0", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "other", value: "2.0", input1: "2.0", input2: nil, input3: nil},
  {user_id: 15, profile_id: nil, footprint_type: "vehicle", value: "2.96", input1: "10000.0", input2: "30.0", input3: "8.89"},
  {user_id: 16, profile_id: nil, footprint_type: "vehicle", value: "5.92", input1: "20000.0", input2: "30.0", input3: "8.89"},
  {user_id: 16, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "air_travel", value: "0.6", input1: "3000.0", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "electricity", value: "1.36", input1: "200.0", input2: "0.1", input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "natural_gas", value: "5.58", input1: "100.0", input2: "0.1", input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "heating", value: "2.03", input1: "200.0", input2: "1.0", input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "propane", value: "0.29", input1: "50.0", input2: "1.0", input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "home", value: "1.86", input1: "2000.0", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "meat", value: "2.07", input1: "2.4", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "dairy", value: "1.17", input1: "2.4", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "grains", value: "0.86", input1: "2.4", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "fruit", value: "0.72", input1: "2.4", input2: nil, input3: nil},
  {user_id: 16, profile_id: nil, footprint_type: "other", value: "2.4", input1: "2.4", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "vehicle", value: "5.98", input1: "20200.0", input2: "30.0", input3: "8.89"},
  {user_id: 17, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "air_travel", value: "4.0", input1: "20000.0", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "electricity", value: "2.04", input1: "300.0", input2: "0.1", input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "natural_gas", value: "5.58", input1: "100.0", input2: "0.1", input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "heating", value: "0.21", input1: "100.0", input2: "4.02", input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "propane", value: "1.15", input1: "200.0", input2: "1.0", input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "meat", value: "1.9", input1: "2.2", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "dairy", value: "0.39", input1: "0.8", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "grains", value: "0.86", input1: "2.4", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "fruit", value: "0.78", input1: "2.6", input2: nil, input3: nil},
  {user_id: 17, profile_id: nil, footprint_type: "other", value: "2.81", input1: "2.8", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "vehicle", value: "12.12", input1: "30000.0", input2: "22.0", input3: "8.89"},
  {user_id: 18, profile_id: nil, footprint_type: "public_transportation", value: "0.03", input1: "100.0", input2: "300.0", input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "air_travel", value: "3.0", input1: "15000.0", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "electricity", value: "0.68", input1: "100.0", input2: "0.1", input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "natural_gas", value: "5.58", input1: "100.0", input2: "0.1", input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "heating", value: "0.43", input1: "50.0", input2: "1.0", input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "propane", value: "0.12", input1: "20.0", input2: "1.0", input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "meat", value: "2.42", input1: "2.8", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "dairy", value: "0.19", input1: "0.4", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "grains", value: "0.5", input1: "1.4", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "fruit", value: "0.12", input1: "0.4", input2: nil, input3: nil},
  {user_id: 18, profile_id: nil, footprint_type: "other", value: "0.4", input1: "0.4", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "vehicle", value: "0.5", input1: "1232.0", input2: "22.0", input3: "8.89"},
  {user_id: 19, profile_id: nil, footprint_type: "public_transportation", value: "0.0", input1: "0.0", input2: "300.0", input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "air_travel", value: "0.05", input1: "232.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "electricity", value: "1.84", input1: "223.0", input2: "0.08", input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "natural_gas", value: "0.1", input1: "23.0", input2: "1.18", input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "heating", value: "0.5", input1: "234.0", input2: "4.02", input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "propane", value: "0.43", input1: "234.0", input2: "3.12", input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "home", value: "0.19", input1: "200.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "meat", value: "0.86", input1: "1.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "dairy", value: "0.49", input1: "1.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "grains", value: "0.36", input1: "1.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "fruit", value: "0.3", input1: "1.0", input2: nil, input3: nil},
  {user_id: 19, profile_id: nil, footprint_type: "other", value: "1.0", input1: "1.0", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "vehicle", value: "0.3", input1: "1000.0", input2: "30.0", input3: "8.89"},
  {user_id: 20, profile_id: nil, footprint_type: "public_transportation", value: "0.09", input1: "300.0", input2: "300.0", input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "air_travel", value: "0.4", input1: "2000.0", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "electricity", value: "2.65", input1: "320.0", input2: "0.08", input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "natural_gas", value: "0.99", input1: "220.0", input2: "1.18", input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "heating", value: "0.72", input1: "340.0", input2: "4.02", input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "propane", value: "0.04", input1: "22.0", input2: "3.12", input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "home", value: "0.84", input1: "900.0", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "meat", value: "1.38", input1: "1.6", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "dairy", value: "0.1", input1: "0.2", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "grains", value: "0.07", input1: "0.2", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "fruit", value: "0.06", input1: "0.2", input2: nil, input3: nil},
  {user_id: 20, profile_id: nil, footprint_type: "other", value: "1.4", input1: "1.4", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "vehicle", value: "1.62", input1: "4000.0", input2: "22.0", input3: "8.89"},
  {user_id: 21, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "air_travel", value: "1.4", input1: "7000.0", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "electricity", value: "1.92", input1: "232.0", input2: "0.08", input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "natural_gas", value: "0.55", input1: "122.0", input2: "1.18", input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "heating", value: "0.04", input1: "21.0", input2: "4.02", input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "propane", value: "0.04", input1: "21.0", input2: "3.12", input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "meat", value: "1.21", input1: "1.4", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "dairy", value: "0.29", input1: "0.6", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "grains", value: "0.5", input1: "1.4", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "fruit", value: "0.12", input1: "0.4", input2: nil, input3: nil},
  {user_id: 21, profile_id: nil, footprint_type: "other", value: "1.6", input1: "1.6", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "vehicle", value: "2.06", input1: "5100.0", input2: "22.0", input3: "8.89"},
  {user_id: 22, profile_id: nil, footprint_type: "public_transportation", value: "0.39", input1: "1291.0", input2: "300.0", input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "air_travel", value: "0.46", input1: "2322.0", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "electricity", value: "2.65", input1: "320.0", input2: "0.08", input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "natural_gas", value: "0.99", input1: "220.0", input2: "1.18", input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "heating", value: "0.04", input1: "21.0", input2: "4.02", input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "propane", value: "0.43", input1: "232.0", input2: "3.12", input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "home", value: "0.84", input1: "900.0", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "meat", value: "1.55", input1: "1.8", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "dairy", value: "0.29", input1: "0.6", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "grains", value: "0.14", input1: "0.4", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "fruit", value: "0.48", input1: "1.6", input2: nil, input3: nil},
  {user_id: 22, profile_id: nil, footprint_type: "other", value: "0.6", input1: "0.6", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "vehicle", value: "1.11", input1: "4000.0", input2: "32.0", input3: "8.89"},
  {user_id: 23, profile_id: nil, footprint_type: "public_transportation", value: "0.0", input1: "0.0", input2: "300.0", input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "air_travel", value: "0.0", input1: "0.0", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "electricity", value: "2.65", input1: "320.0", input2: "0.08", input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "natural_gas", value: "0.54", input1: "120.0", input2: "1.18", input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "heating", value: "0.49", input1: "231.0", input2: "4.02", input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "propane", value: "0.0", input1: "0.0", input2: "3.12", input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "home", value: "1.96", input1: "2110.0", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "meat", value: "1.21", input1: "1.4", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "dairy", value: "0.68", input1: "1.4", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "grains", value: "0.14", input1: "0.4", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "fruit", value: "0.18", input1: "0.6", input2: nil, input3: nil},
  {user_id: 23, profile_id: nil, footprint_type: "other", value: "1.4", input1: "1.4", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "vehicle", value: "9.46", input1: "23423.0", input2: "22.0", input3: "8.89"},
  {user_id: 24, profile_id: nil, footprint_type: "public_transportation", value: "0.01", input1: "23.0", input2: "300.0", input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "air_travel", value: "0.01", input1: "32.0", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "electricity", value: "1.92", input1: "232.0", input2: "0.08", input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "natural_gas", value: "1.04", input1: "232.0", input2: "1.18", input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "heating", value: "0.04", input1: "21.0", input2: "4.02", input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "propane", value: "0.22", input1: "121.0", input2: "3.12", input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "home", value: "0.19", input1: "200.0", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "meat", value: "1.38", input1: "1.6", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "dairy", value: "0.88", input1: "1.8", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "grains", value: "0.65", input1: "1.8", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "fruit", value: "0.54", input1: "1.8", input2: nil, input3: nil},
  {user_id: 24, profile_id: nil, footprint_type: "other", value: "1.8", input1: "1.8", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "vehicle", value: "2.06", input1: "5100.0", input2: "22.0", input3: "8.89"},
  {user_id: 25, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "air_travel", value: "0.46", input1: "2323.0", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "electricity", value: "2.65", input1: "320.0", input2: "0.08", input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "natural_gas", value: "0.9", input1: "200.0", input2: "1.18", input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "heating", value: "0.04", input1: "20.0", input2: "4.02", input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "propane", value: "0.04", input1: "21.0", input2: "3.12", input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "home", value: "0.74", input1: "800.0", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "meat", value: "1.38", input1: "1.6", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "dairy", value: "0.68", input1: "1.4", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "grains", value: "0.22", input1: "0.6", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "fruit", value: "0.18", input1: "0.6", input2: nil, input3: nil},
  {user_id: 25, profile_id: nil, footprint_type: "other", value: "1.4", input1: "1.4", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "vehicle", value: "0.53", input1: "1322.0", input2: "22.0", input3: "8.89"},
  {user_id: 26, profile_id: nil, footprint_type: "public_transportation", value: "0.13", input1: "423.0", input2: "300.0", input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "air_travel", value: "0.47", input1: "2343.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "electricity", value: "19.37", input1: "2343.0", input2: "0.08", input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "natural_gas", value: "1.9", input1: "423.0", input2: "1.18", input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "heating", value: "0.05", input1: "22.0", input2: "4.02", input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "propane", value: "0.04", input1: "22.0", input2: "3.12", input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "home", value: "0.39", input1: "423.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "meat", value: "0.86", input1: "1.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "dairy", value: "0.49", input1: "1.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "grains", value: "0.36", input1: "1.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "fruit", value: "0.3", input1: "1.0", input2: nil, input3: nil},
  {user_id: 26, profile_id: nil, footprint_type: "other", value: "1.0", input1: "1.0", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "vehicle", value: "2.06", input1: "5100.0", input2: "22.0", input3: "8.89"},
  {user_id: 27, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "200.0", input2: "300.0", input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "air_travel", value: "0.86", input1: "4300.0", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "electricity", value: "2.66", input1: "322.0", input2: "0.08", input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "natural_gas", value: "0.1", input1: "23.0", input2: "1.18", input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "heating", value: "0.09", input1: "43.0", input2: "4.02", input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "propane", value: "0.08", input1: "43.0", input2: "3.12", input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "home", value: "2.18", input1: "2343.0", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "meat", value: "1.21", input1: "1.4", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "dairy", value: "0.58", input1: "1.2", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "grains", value: "0.22", input1: "0.6", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "fruit", value: "0.18", input1: "0.6", input2: nil, input3: nil},
  {user_id: 27, profile_id: nil, footprint_type: "other", value: "1.0", input1: "1.0", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "vehicle", value: "2.06", input1: "5100.0", input2: "22.0", input3: "8.89"},
  {user_id: 28, profile_id: nil, footprint_type: "public_transportation", value: "0.06", input1: "210.0", input2: "300.0", input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "air_travel", value: "0.64", input1: "3203.0", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "electricity", value: "0.02", input1: "32.0", input2: "1.0", input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "natural_gas", value: "1.71", input1: "322.0", input2: "1.0", input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "heating", value: "0.66", input1: "312.0", input2: "4.02", input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "propane", value: "0.18", input1: "32.0", input2: "1.0", input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "home", value: "0.3", input1: "321.0", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "meat", value: "1.21", input1: "1.4", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "dairy", value: "0.68", input1: "1.4", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "grains", value: "0.22", input1: "0.6", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "fruit", value: "0.48", input1: "1.6", input2: nil, input3: nil},
  {user_id: 28, profile_id: nil, footprint_type: "other", value: "0.6", input1: "0.6", input2: nil, input3: nil}
])
Profile.create!([
  {user_id: 1, total_value: "23.19"},
  {user_id: 2, total_value: "31.29"},
  {user_id: 3, total_value: "43.92"},
  {user_id: 9, total_value: "41.56"},
  {user_id: 7, total_value: "28.69"},
  {user_id: 15, total_value: "30.97"},
  {user_id: 16, total_value: "24.92"},
  {user_id: 17, total_value: "26.5"},
  {user_id: 18, total_value: "26.33"},
  {user_id: 19, total_value: "6.62"},
  {user_id: 20, total_value: "9.04"},
  {user_id: 21, total_value: "10.09"},
  {user_id: 22, total_value: "10.92"},
  {user_id: 23, total_value: "10.36"},
  {user_id: 24, total_value: "18.14"},
  {user_id: 25, total_value: "10.81"},
  {user_id: 26, total_value: "25.89"},
  {user_id: 27, total_value: "11.28"},
  {user_id: 28, total_value: "8.82"}
])
